"""El esquema inicial del ERP.

Congela la estructura que estaba repartida entre plataforma/modelo.sql y la tabla
COLUMNAS de app.py. A partir de acá, todo cambio de esquema es una migración nueva
y nada se toca a mano en la base.
"""
from alembic import op
import sqlalchemy as sa

revision = '0001_esquema_inicial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('clientes',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('nombre_pila', sa.Text(), nullable=False),
        sa.Column('apellido', sa.Text(), nullable=True),
        sa.Column('nombre', sa.Text(), nullable=False),
        sa.Column('telefono', sa.Text(), nullable=True),
        sa.Column('cedula', sa.Text(), nullable=True),
        sa.Column('correo', sa.Text(), nullable=True),
        sa.Column('origen_excel', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('ciudad', sa.Text(), nullable=True),
        sa.Column('estado', sa.Text(), nullable=True),
        sa.Column('canal_habitual', sa.Text(), nullable=True),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
        sa.Column('origen', sa.Text(), nullable=True),
        sa.Column('origen_nota', sa.Text(), nullable=True),
        sa.Column('porche_tamano', sa.Text(), nullable=True),
        sa.Column('porche_version', sa.Text(), nullable=True),
        sa.Column('referido_id', sa.Integer(), nullable=True),
    )
    op.create_table('config',
        sa.Column('clave', sa.Text(), nullable=True, primary_key=True),
        sa.Column('valor', sa.Text(), nullable=True),
    )
    op.create_table('cuentas',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('codigo', sa.Text(), nullable=True),
        sa.Column('nombre', sa.Text(), nullable=False, unique=True),
        sa.Column('moneda', sa.Text(), nullable=True, server_default=sa.text("'USD'")),
        sa.Column('tipo', sa.Text(), nullable=True, server_default=sa.text("'operativa'")),
        sa.Column('saldo_inicial', sa.Float(), nullable=True, server_default=sa.text('0')),
        sa.Column('fecha_corte', sa.Text(), nullable=True),
        sa.Column('personal', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('activa', sa.Integer(), nullable=True, server_default=sa.text('1')),
        sa.Column('orden', sa.Integer(), nullable=True, server_default=sa.text('100')),
        sa.Column('cobra', sa.Integer(), nullable=True, server_default=sa.text('1')),
    )
    op.create_table('despachadores',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('nombre', sa.Text(), nullable=False, unique=True),
        sa.Column('telefono', sa.Text(), nullable=True),
        sa.Column('activo', sa.Integer(), nullable=False, server_default=sa.text('1')),
        sa.Column('notas', sa.Text(), nullable=True),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
    )
    op.create_table('faltas',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('nombre', sa.Text(), nullable=False),
        sa.Column('fecha', sa.Text(), nullable=False),
        sa.Column('nota', sa.Text(), nullable=True),
        sa.Column('usuario_id', sa.Integer(), nullable=True),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
        sa.UniqueConstraint('nombre', 'fecha'),
    )
    op.create_table('intentos',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('usuario', sa.Text(), nullable=True),
        sa.Column('ip', sa.Text(), nullable=True),
        sa.Column('cuando', sa.Text(), nullable=False, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
    )
    op.create_table('notas_taller',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('fecha', sa.Text(), nullable=False),
        sa.Column('texto', sa.Text(), nullable=False),
        sa.Column('usuario_id', sa.Integer(), nullable=True),
        sa.Column('visto', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
        sa.Column('produccion_id', sa.Integer(), nullable=True),
        sa.Column('resuelto', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('resuelto_en', sa.Text(), nullable=True),
    )
    op.create_table('pagos_despachador',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('despachador', sa.Text(), nullable=False),
        sa.Column('fecha', sa.Text(), nullable=False),
        sa.Column('monto', sa.Float(), nullable=False),
        sa.Column('entregas', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('nota', sa.Text(), nullable=True),
        sa.Column('usuario_id', sa.Integer(), nullable=True),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
    )
    op.create_table('productos',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('sku', sa.Text(), nullable=True, unique=True),
        sa.Column('nombre', sa.Text(), nullable=False),
        sa.Column('categoria', sa.Text(), nullable=True),
        sa.Column('variante', sa.Text(), nullable=True),
        sa.Column('descripcion', sa.Text(), nullable=True),
        sa.Column('precio', sa.Float(), nullable=True),
        sa.Column('precio_par', sa.Float(), nullable=True),
        sa.Column('costo', sa.Float(), nullable=True),
        sa.Column('activo', sa.Integer(), nullable=True, server_default=sa.text('1')),
        sa.Column('orden', sa.Integer(), nullable=True, server_default=sa.text('100')),
        sa.Column('tipo', sa.Text(), nullable=True, server_default=sa.text("'producto'")),
        sa.Column('requiere_color', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('permite_malla', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('permite_personalizacion', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('stock', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('minimo', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('foto', sa.Text(), nullable=True),
        sa.Column('descripcion_larga', sa.Text(), nullable=True),
        sa.Column('peso_kg', sa.Float(), nullable=True),
        sa.Column('foto_rosado', sa.Text(), nullable=True),
        sa.Column('canales', sa.Text(), nullable=True),
        sa.Column('proveedor', sa.Text(), nullable=True),
        sa.Column('unidad', sa.Text(), nullable=True),
    )
    op.create_table('proveedores',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('nombre', sa.Text(), nullable=False),
        sa.Column('que_vende', sa.Text(), nullable=True),
        sa.Column('contacto', sa.Text(), nullable=True),
        sa.Column('telefono', sa.Text(), nullable=True),
        sa.Column('correo', sa.Text(), nullable=True),
        sa.Column('ciudad', sa.Text(), nullable=True),
        sa.Column('direccion', sa.Text(), nullable=True),
        sa.Column('forma_pago', sa.Text(), nullable=True),
        sa.Column('precios', sa.Text(), nullable=True),
        sa.Column('notas', sa.Text(), nullable=True),
        sa.Column('activo', sa.Integer(), nullable=False, server_default=sa.text('1')),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
    )
    op.create_table('registro_ventas',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('fecha', sa.Text(), nullable=False),
        sa.Column('cliente', sa.Text(), nullable=True),
        sa.Column('producto', sa.Text(), nullable=True),
        sa.Column('precio', sa.Float(), nullable=True),
        sa.Column('cantidad', sa.Float(), nullable=True, server_default=sa.text('1')),
        sa.Column('facturacion', sa.Float(), nullable=True),
        sa.Column('forma_pago', sa.Text(), nullable=True),
        sa.Column('origen', sa.Text(), nullable=True, server_default=sa.text("'excel'")),
        sa.Column('fila_excel', sa.Integer(), nullable=True),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
    )
    op.create_table('resultados_mes',
        sa.Column('mes', sa.Text(), nullable=True, primary_key=True),
        sa.Column('facturacion', sa.Float(), nullable=True, server_default=sa.text('0')),
        sa.Column('unidades', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('gastos', sa.Float(), nullable=True, server_default=sa.text('0')),
        sa.Column('sueldo', sa.Float(), nullable=True, server_default=sa.text('0')),
        sa.Column('arrastre', sa.Float(), nullable=True, server_default=sa.text('0')),
        sa.Column('contexto', sa.Text(), nullable=True),
        sa.Column('nota', sa.Text(), nullable=True),
    )
    op.create_table('tarifas',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('zona', sa.Text(), nullable=False, unique=True),
        sa.Column('tarifa', sa.Float(), nullable=False, server_default=sa.text('0')),
        sa.Column('pago_despachador', sa.Float(), nullable=True),
        sa.Column('notas', sa.Text(), nullable=True),
        sa.Column('orden', sa.Integer(), nullable=True, server_default=sa.text('0')),
    )
    op.create_table('tasas',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('fecha_valor', sa.Text(), nullable=False),
        sa.Column('valor', sa.Float(), nullable=False),
        sa.Column('fuente', sa.Text(), nullable=False),
        sa.Column('obtenido_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
        sa.Column('manual', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('usuario_id', sa.Integer(), nullable=True),
        sa.Column('nota', sa.Text(), nullable=True),
        sa.UniqueConstraint('fecha_valor', 'fuente'),
    )
    op.create_table('usuarios',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('nombre', sa.Text(), nullable=False),
        sa.Column('rol', sa.Text(), nullable=False),
        sa.Column('activo', sa.Integer(), nullable=True, server_default=sa.text('1')),
        sa.Column('usuario', sa.Text(), nullable=True),
        sa.Column('clave_hash', sa.Text(), nullable=True),
        sa.Column('creado_en', sa.Text(), nullable=True),
        sa.Column('despachador', sa.Text(), nullable=True),
    )
    op.create_table('compromisos',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('nombre', sa.Text(), nullable=False),
        sa.Column('categoria', sa.Text(), nullable=True),
        sa.Column('subcategoria', sa.Text(), nullable=True),
        sa.Column('proveedor', sa.Text(), nullable=True),
        sa.Column('monto', sa.Float(), nullable=True),
        sa.Column('moneda', sa.Text(), nullable=True, server_default=sa.text("'USD'")),
        sa.Column('frecuencia', sa.Text(), nullable=False),
        sa.Column('dia', sa.Integer(), nullable=True),
        sa.Column('cuenta_id', sa.Integer(), sa.ForeignKey('cuentas.id'), nullable=True),
        sa.Column('activo', sa.Integer(), nullable=True, server_default=sa.text('1')),
        sa.Column('nota', sa.Text(), nullable=True),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
        sa.Column('precio_unitario', sa.Float(), nullable=True),
        sa.Column('unidad', sa.Text(), nullable=True),
    )
    op.create_table('direcciones',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('cliente_id', sa.Integer(), sa.ForeignKey('clientes.id', ondelete='CASCADE'), nullable=False),
        sa.Column('etiqueta', sa.Text(), nullable=True),
        sa.Column('direccion', sa.Text(), nullable=False),
        sa.Column('zona', sa.Text(), nullable=True),
        sa.Column('municipio', sa.Text(), nullable=True),
        sa.Column('ciudad', sa.Text(), nullable=True),
        sa.Column('estado', sa.Text(), nullable=True),
        sa.Column('maps', sa.Text(), nullable=True),
        sa.Column('principal', sa.Integer(), nullable=True, server_default=sa.text('0')),
    )
    op.create_table('mascotas',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('cliente_id', sa.Integer(), sa.ForeignKey('clientes.id', ondelete='CASCADE'), nullable=False),
        sa.Column('nombre', sa.Text(), nullable=False),
        sa.Column('raza', sa.Text(), nullable=True),
        sa.Column('fecha_nacimiento', sa.Text(), nullable=True),
        sa.Column('cumple_mes_dia', sa.Text(), nullable=True),
        sa.Column('revisar', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('peso_kg', sa.Float(), nullable=True),
        sa.Column('notas', sa.Text(), nullable=True),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
    )
    op.create_table('movimientos',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('fecha', sa.Text(), nullable=False),
        sa.Column('tipo', sa.Text(), nullable=False),
        sa.Column('cuenta_origen_id', sa.Integer(), sa.ForeignKey('cuentas.id'), nullable=True),
        sa.Column('cuenta_destino_id', sa.Integer(), sa.ForeignKey('cuentas.id'), nullable=True),
        sa.Column('monto_usd', sa.Float(), nullable=False),
        sa.Column('monto_real', sa.Float(), nullable=True),
        sa.Column('moneda', sa.Text(), nullable=True, server_default=sa.text("'USD'")),
        sa.Column('tasa', sa.Float(), nullable=True),
        sa.Column('concepto', sa.Text(), nullable=True),
        sa.Column('despachador', sa.Text(), nullable=True),
        sa.Column('usuario_id', sa.Integer(), sa.ForeignKey('usuarios.id'), nullable=True),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
        sa.Column('categoria', sa.Text(), nullable=True),
        sa.Column('comprobante', sa.Text(), nullable=True),
        sa.Column('notas', sa.Text(), nullable=True),
        sa.Column('subcategoria', sa.Text(), nullable=True),
    )
    op.create_table('notas_cliente',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('cliente_id', sa.Integer(), sa.ForeignKey('clientes.id', ondelete='CASCADE'), nullable=False),
        sa.Column('tipo', sa.Text(), nullable=False),
        sa.Column('texto', sa.Text(), nullable=False),
        sa.Column('mostrar_en_orden', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('mostrar_logistica', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('privada', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('autor_id', sa.Integer(), sa.ForeignKey('usuarios.id'), nullable=True),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
    )
    op.create_table('ordenes',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('numero', sa.Text(), nullable=True, unique=True),
        sa.Column('tipo', sa.Text(), nullable=True, server_default=sa.text("'venta'")),
        sa.Column('cliente_id', sa.Integer(), sa.ForeignKey('clientes.id'), nullable=True),
        sa.Column('canal', sa.Text(), nullable=True),
        sa.Column('creada_por', sa.Integer(), sa.ForeignKey('usuarios.id'), nullable=True),
        sa.Column('conversacion', sa.Text(), nullable=True),
        sa.Column('campana', sa.Text(), nullable=True),
        sa.Column('ref_externa', sa.Text(), nullable=True),
        sa.Column('estado', sa.Text(), nullable=True, server_default=sa.text("'nueva'")),
        sa.Column('estado_pago', sa.Text(), nullable=True, server_default=sa.text("'sin_pago'")),
        sa.Column('subtotal', sa.Float(), nullable=True, server_default=sa.text('0')),
        sa.Column('descuento', sa.Float(), nullable=True, server_default=sa.text('0')),
        sa.Column('motivo_descuento', sa.Text(), nullable=True),
        sa.Column('iva', sa.Float(), nullable=True, server_default=sa.text('0')),
        sa.Column('delivery', sa.Float(), nullable=True, server_default=sa.text('0')),
        sa.Column('total', sa.Float(), nullable=True, server_default=sa.text('0')),
        sa.Column('tasa_bcv', sa.Float(), nullable=True),
        sa.Column('comision', sa.Float(), nullable=True, server_default=sa.text('0')),
        sa.Column('tipo_entrega', sa.Text(), nullable=True),
        sa.Column('direccion', sa.Text(), nullable=True),
        sa.Column('zona', sa.Text(), nullable=True),
        sa.Column('ciudad', sa.Text(), nullable=True),
        sa.Column('maps', sa.Text(), nullable=True),
        sa.Column('receptor_nombre', sa.Text(), nullable=True),
        sa.Column('receptor_telefono', sa.Text(), nullable=True),
        sa.Column('despachador', sa.Text(), nullable=True),
        sa.Column('agencia', sa.Text(), nullable=True),
        sa.Column('guia', sa.Text(), nullable=True),
        sa.Column('fecha_prometida', sa.Text(), nullable=True),
        sa.Column('franja', sa.Text(), nullable=True),
        sa.Column('fecha_entrega', sa.Text(), nullable=True),
        sa.Column('fecha_pago', sa.Text(), nullable=True),
        sa.Column('promo_envio', sa.Text(), nullable=True),
        sa.Column('notas_entrega', sa.Text(), nullable=True),
        sa.Column('notas', sa.Text(), nullable=True),
        sa.Column('distribuidor', sa.Text(), nullable=True),
        sa.Column('saldo_concepto', sa.Text(), nullable=True),
        sa.Column('forma_pago_prevista', sa.Text(), nullable=True),
        sa.Column('modalidad_envio', sa.Text(), nullable=True),
        sa.Column('monto_contra_entrega', sa.Float(), nullable=True, server_default=sa.text('0')),
        sa.Column('origen_excel', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('costo_productos', sa.Float(), nullable=True, server_default=sa.text('0')),
        sa.Column('costo_entrega', sa.Float(), nullable=True, server_default=sa.text('0')),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
        sa.Column('actualizado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
        sa.Column('despachador_pagado', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('despachador_pago_id', sa.Integer(), nullable=True),
        sa.Column('en_registro', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('factura_fecha', sa.Text(), nullable=True),
        sa.Column('factura_hecha', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('factura_numero', sa.Text(), nullable=True),
        sa.Column('factura_por', sa.Integer(), nullable=True),
        sa.Column('pago_despachador', sa.Float(), nullable=True),
        sa.Column('receptor_cedula', sa.Text(), nullable=True),
        sa.Column('receptor_correo', sa.Text(), nullable=True),
        sa.Column('requiere_factura', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('viaje_id', sa.Integer(), nullable=True),
    )
    op.create_table('produccion',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('producto_id', sa.Integer(), sa.ForeignKey('productos.id'), nullable=True),
        sa.Column('fecha_pedido', sa.Text(), nullable=False),
        sa.Column('fecha_esperada', sa.Text(), nullable=True),
        sa.Column('responsable', sa.Text(), nullable=True),
        sa.Column('costo', sa.Float(), nullable=True),
        sa.Column('nota', sa.Text(), nullable=True),
        sa.Column('estado', sa.Text(), nullable=True, server_default=sa.text("'en_proceso'")),
        sa.Column('usuario_id', sa.Integer(), sa.ForeignKey('usuarios.id'), nullable=True),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
        sa.Column('recibido_en', sa.Text(), nullable=True),
        sa.Column('pieza', sa.Text(), nullable=True),
        sa.Column('pagado', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('barnizado', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('descripcion', sa.Text(), nullable=True),
        sa.Column('cantidad', sa.Integer(), nullable=False, server_default=sa.text('1')),
        sa.Column('fecha_pago', sa.Text(), nullable=True),
        sa.Column('faltaron', sa.Integer(), nullable=True),
        sa.Column('recibido', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('tipo_pedido', sa.Text(), nullable=True, server_default=sa.text("'produccion'")),
    )
    op.create_table('producto_fotos',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('producto_id', sa.Integer(), sa.ForeignKey('productos.id', ondelete='CASCADE'), nullable=False),
        sa.Column('archivo', sa.Text(), nullable=False),
        sa.Column('etiqueta', sa.Text(), nullable=True),
        sa.Column('orden', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
        sa.Column('tipo', sa.Text(), nullable=False, server_default=sa.text("'sin_fondo'")),
    )
    op.create_table('proveedor_items',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('proveedor_id', sa.Integer(), sa.ForeignKey('proveedores.id', ondelete='CASCADE'), nullable=False),
        sa.Column('item', sa.Text(), nullable=False),
        sa.Column('precio', sa.Float(), nullable=True),
        sa.Column('unidad', sa.Text(), nullable=True),
        sa.Column('orden', sa.Integer(), nullable=True, server_default=sa.text('0')),
    )
    op.create_table('receta',
        sa.Column('producto_id', sa.Integer(), sa.ForeignKey('productos.id'), nullable=False, primary_key=True),
        sa.Column('insumo_id', sa.Integer(), sa.ForeignKey('productos.id'), nullable=False, primary_key=True),
        sa.Column('cantidad', sa.Float(), nullable=False, server_default=sa.text('1')),
        sa.PrimaryKeyConstraint('producto_id', 'insumo_id'),
    )
    op.create_table('seguimientos',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('cliente_id', sa.Integer(), sa.ForeignKey('clientes.id', ondelete='CASCADE'), nullable=False),
        sa.Column('tipo', sa.Text(), nullable=False),
        sa.Column('clave', sa.Text(), nullable=True, unique=True),
        sa.Column('resultado', sa.Text(), nullable=True),
        sa.Column('nota', sa.Text(), nullable=True),
        sa.Column('posponer_hasta', sa.Text(), nullable=True),
        sa.Column('intentos', sa.Integer(), nullable=False, server_default=sa.text('1')),
        sa.Column('usuario_id', sa.Integer(), sa.ForeignKey('usuarios.id'), nullable=True),
        sa.Column('hecho_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
    )
    op.create_table('sesiones',
        sa.Column('ficha', sa.Text(), nullable=True, primary_key=True),
        sa.Column('usuario_id', sa.Integer(), sa.ForeignKey('usuarios.id'), nullable=False),
        sa.Column('creada_en', sa.Text(), nullable=False, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
        sa.Column('vence_en', sa.Text(), nullable=False),
        sa.Column('visto_en', sa.Text(), nullable=True),
    )
    op.create_table('viajes_agencia',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('fecha', sa.Text(), nullable=False),
        sa.Column('despachador', sa.Text(), nullable=False),
        sa.Column('agencia', sa.Text(), nullable=True),
        sa.Column('monto', sa.Float(), nullable=False, server_default=sa.text('0')),
        sa.Column('pedidos', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('pagado', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('pago_id', sa.Integer(), sa.ForeignKey('pagos_despachador.id'), nullable=True),
        sa.Column('nota', sa.Text(), nullable=True),
        sa.Column('usuario_id', sa.Integer(), nullable=True),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
    )
    op.create_table('abonos_produccion',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('produccion_id', sa.Integer(), sa.ForeignKey('produccion.id', ondelete='CASCADE'), nullable=False),
        sa.Column('fecha', sa.Text(), nullable=False),
        sa.Column('monto', sa.Float(), nullable=False),
        sa.Column('forma', sa.Text(), nullable=True),
        sa.Column('nota', sa.Text(), nullable=True),
        sa.Column('usuario_id', sa.Integer(), nullable=True),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
        sa.Column('gasto_id', sa.Integer(), nullable=True),
    )
    op.create_table('credito_cliente',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('cliente_id', sa.Integer(), sa.ForeignKey('clientes.id'), nullable=False),
        sa.Column('fecha', sa.Text(), nullable=False),
        sa.Column('monto', sa.Float(), nullable=False),
        sa.Column('motivo', sa.Text(), nullable=True),
        sa.Column('orden_id', sa.Integer(), sa.ForeignKey('ordenes.id'), nullable=True),
        sa.Column('usuario_id', sa.Integer(), nullable=True),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
    )
    op.create_table('fotos',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('archivo', sa.Text(), nullable=False),
        sa.Column('cliente_id', sa.Integer(), sa.ForeignKey('clientes.id'), nullable=True),
        sa.Column('orden_id', sa.Integer(), sa.ForeignKey('ordenes.id'), nullable=True),
        sa.Column('producto_id', sa.Integer(), sa.ForeignKey('productos.id'), nullable=True),
        sa.Column('canal', sa.Text(), nullable=True, server_default=sa.text("'whatsapp'")),
        sa.Column('permiso', sa.Text(), nullable=True, server_default=sa.text("'sin_confirmar'")),
        sa.Column('instagram', sa.Text(), nullable=True),
        sa.Column('enlace_publicacion', sa.Text(), nullable=True),
        sa.Column('nota', sa.Text(), nullable=True),
        sa.Column('fecha', sa.Text(), nullable=True),
        sa.Column('usuario_id', sa.Integer(), sa.ForeignKey('usuarios.id'), nullable=True),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
    )
    op.create_table('gastos',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('fecha', sa.Text(), nullable=False),
        sa.Column('monto_usd', sa.Float(), nullable=False),
        sa.Column('monto_real', sa.Float(), nullable=True),
        sa.Column('moneda', sa.Text(), nullable=True, server_default=sa.text("'USD'")),
        sa.Column('tasa', sa.Float(), nullable=True),
        sa.Column('categoria', sa.Text(), nullable=False),
        sa.Column('subcategoria', sa.Text(), nullable=True),
        sa.Column('descripcion', sa.Text(), nullable=True),
        sa.Column('proveedor', sa.Text(), nullable=True),
        sa.Column('cuenta_id', sa.Integer(), sa.ForeignKey('cuentas.id'), nullable=True),
        sa.Column('orden_id', sa.Integer(), sa.ForeignKey('ordenes.id'), nullable=True),
        sa.Column('recurrente', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('comprobante', sa.Text(), nullable=True),
        sa.Column('notas', sa.Text(), nullable=True),
        sa.Column('usuario_id', sa.Integer(), sa.ForeignKey('usuarios.id'), nullable=True),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
        sa.Column('cantidad', sa.Float(), nullable=True),
        sa.Column('compra_grande', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('unidad', sa.Text(), nullable=True),
    )
    op.create_table('historial',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('orden_id', sa.Integer(), sa.ForeignKey('ordenes.id', ondelete='CASCADE'), nullable=False),
        sa.Column('usuario_id', sa.Integer(), sa.ForeignKey('usuarios.id'), nullable=True),
        sa.Column('accion', sa.Text(), nullable=False),
        sa.Column('detalle', sa.Text(), nullable=True),
        sa.Column('motivo', sa.Text(), nullable=True),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
    )
    op.create_table('incidencias',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('orden_id', sa.Integer(), sa.ForeignKey('ordenes.id', ondelete='CASCADE'), nullable=False),
        sa.Column('clase', sa.Text(), nullable=True, server_default=sa.text("'incidencia'")),
        sa.Column('tipo', sa.Text(), nullable=True),
        sa.Column('descripcion', sa.Text(), nullable=True),
        sa.Column('responsable', sa.Text(), nullable=True),
        sa.Column('estado', sa.Text(), nullable=True, server_default=sa.text("'abierta'")),
        sa.Column('resolucion', sa.Text(), nullable=True),
        sa.Column('autor_id', sa.Integer(), sa.ForeignKey('usuarios.id'), nullable=True),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
        sa.Column('cerrado_en', sa.Text(), nullable=True),
    )
    op.create_table('mov_inventario',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('producto_id', sa.Integer(), sa.ForeignKey('productos.id'), nullable=False),
        sa.Column('fecha', sa.Text(), nullable=False),
        sa.Column('tipo', sa.Text(), nullable=False),
        sa.Column('cantidad', sa.Integer(), nullable=False),
        sa.Column('orden_id', sa.Integer(), sa.ForeignKey('ordenes.id'), nullable=True),
        sa.Column('nota', sa.Text(), nullable=True),
        sa.Column('usuario_id', sa.Integer(), sa.ForeignKey('usuarios.id'), nullable=True),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
        sa.Column('color', sa.Text(), nullable=True),
        sa.Column('lote', sa.Text(), nullable=True),
    )
    op.create_table('orden_lineas',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('orden_id', sa.Integer(), sa.ForeignKey('ordenes.id', ondelete='CASCADE'), nullable=False),
        sa.Column('producto_id', sa.Integer(), sa.ForeignKey('productos.id'), nullable=True),
        sa.Column('nombre', sa.Text(), nullable=True),
        sa.Column('cantidad', sa.Float(), nullable=True, server_default=sa.text('1')),
        sa.Column('precio', sa.Float(), nullable=True, server_default=sa.text('0')),
        sa.Column('costo', sa.Float(), nullable=True, server_default=sa.text('0')),
        sa.Column('descuento', sa.Float(), nullable=True, server_default=sa.text('0')),
        sa.Column('personalizacion', sa.Text(), nullable=True),
        sa.Column('color', sa.Text(), nullable=True),
        sa.Column('malla', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('extras', sa.Float(), nullable=True, server_default=sa.text('0')),
        sa.Column('total', sa.Float(), nullable=True, server_default=sa.text('0')),
        sa.Column('forma_pago', sa.Text(), nullable=True),
    )
    op.create_table('packs',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('cliente_id', sa.Integer(), sa.ForeignKey('clientes.id'), nullable=False),
        sa.Column('orden_id', sa.Integer(), sa.ForeignKey('ordenes.id'), nullable=True),
        sa.Column('producto_id', sa.Integer(), sa.ForeignKey('productos.id'), nullable=True),
        sa.Column('tamano', sa.Text(), nullable=True),
        sa.Column('unidades', sa.Integer(), nullable=False),
        sa.Column('entregadas_inicio', sa.Integer(), nullable=True, server_default=sa.text('1')),
        sa.Column('estado', sa.Text(), nullable=True, server_default=sa.text("'activo'")),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
        sa.Column('deliveries_prepagados', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('delivery_pagado', sa.Integer(), nullable=True),
        sa.Column('delivery_programado', sa.Float(), nullable=True),
        sa.Column('despachador_programado', sa.Text(), nullable=True),
        sa.Column('fecha_programada', sa.Text(), nullable=True),
        sa.Column('nota_programada', sa.Text(), nullable=True),
        sa.Column('retiro_programado', sa.Integer(), nullable=True),
        sa.Column('tipo_programado', sa.Text(), nullable=True),
    )
    op.create_table('pagos',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('orden_id', sa.Integer(), sa.ForeignKey('ordenes.id', ondelete='CASCADE'), nullable=False),
        sa.Column('forma', sa.Text(), nullable=False),
        sa.Column('monto_usd', sa.Float(), nullable=False),
        sa.Column('monto_real', sa.Float(), nullable=True),
        sa.Column('moneda', sa.Text(), nullable=True, server_default=sa.text("'USD'")),
        sa.Column('tasa', sa.Float(), nullable=True),
        sa.Column('cuenta', sa.Text(), nullable=True),
        sa.Column('referencia', sa.Text(), nullable=True),
        sa.Column('comprobante', sa.Text(), nullable=True),
        sa.Column('fecha', sa.Text(), nullable=True),
        sa.Column('estado', sa.Text(), nullable=True, server_default=sa.text("'por_confirmar'")),
        sa.Column('verificado_tina', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('motivo_revision', sa.Text(), nullable=True),
        sa.Column('confirmado_por', sa.Integer(), sa.ForeignKey('usuarios.id'), nullable=True),
        sa.Column('confirmado_en', sa.Text(), nullable=True),
        sa.Column('en_cashflow', sa.Integer(), nullable=False, server_default=sa.text('0')),
    )
    op.create_table('compromisos_pagos',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('compromiso_id', sa.Integer(), sa.ForeignKey('compromisos.id', ondelete='CASCADE'), nullable=False),
        sa.Column('vence', sa.Text(), nullable=False),
        sa.Column('gasto_id', sa.Integer(), sa.ForeignKey('gastos.id'), nullable=True),
        sa.Column('pagado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
        sa.Column('motivo', sa.Text(), nullable=True),
        sa.UniqueConstraint('compromiso_id', 'vence'),
    )
    op.create_table('entregas_repuesto',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('pack_id', sa.Integer(), sa.ForeignKey('packs.id', ondelete='CASCADE'), nullable=False),
        sa.Column('fecha', sa.Text(), nullable=False),
        sa.Column('tipo_entrega', sa.Text(), nullable=True),
        sa.Column('despachador', sa.Text(), nullable=True),
        sa.Column('delivery_cobrado', sa.Float(), nullable=True, server_default=sa.text('0')),
        sa.Column('notas', sa.Text(), nullable=True),
        sa.Column('usuario_id', sa.Integer(), sa.ForeignKey('usuarios.id'), nullable=True),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
    )
    op.create_table('repuestos_prepagados',
        sa.Column('id', sa.Integer(), nullable=True, primary_key=True),
        sa.Column('cliente_id', sa.Integer(), sa.ForeignKey('clientes.id'), nullable=False),
        sa.Column('orden_id', sa.Integer(), sa.ForeignKey('ordenes.id'), nullable=True),
        sa.Column('linea_id', sa.Integer(), sa.ForeignKey('orden_lineas.id'), nullable=True),
        sa.Column('producto_id', sa.Integer(), sa.ForeignKey('productos.id'), nullable=True),
        sa.Column('tamano', sa.Text(), nullable=True),
        sa.Column('pagado_en', sa.Text(), nullable=True),
        sa.Column('fecha_programada', sa.Text(), nullable=True),
        sa.Column('tipo_entrega', sa.Text(), nullable=True),
        sa.Column('despachador', sa.Text(), nullable=True),
        sa.Column('entregado_en', sa.Text(), nullable=True),
        sa.Column('notas', sa.Text(), nullable=True),
        sa.Column('usuario_id', sa.Integer(), sa.ForeignKey('usuarios.id'), nullable=True),
        sa.Column('creado_en', sa.Text(), nullable=True, server_default=sa.text("to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')")),
        sa.Column('agencia', sa.Text(), nullable=True),
        sa.Column('delivery', sa.Float(), nullable=False, server_default=sa.text('0')),
        sa.Column('delivery_forma', sa.Text(), nullable=True),
        sa.Column('delivery_pagado', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('en_ruta', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('envio', sa.Text(), nullable=True),
        sa.Column('monto', sa.Float(), nullable=True),
    )


def downgrade():
    op.drop_table('repuestos_prepagados')
    op.drop_table('entregas_repuesto')
    op.drop_table('compromisos_pagos')
    op.drop_table('pagos')
    op.drop_table('packs')
    op.drop_table('orden_lineas')
    op.drop_table('mov_inventario')
    op.drop_table('incidencias')
    op.drop_table('historial')
    op.drop_table('gastos')
    op.drop_table('fotos')
    op.drop_table('credito_cliente')
    op.drop_table('abonos_produccion')
    op.drop_table('viajes_agencia')
    op.drop_table('sesiones')
    op.drop_table('seguimientos')
    op.drop_table('receta')
    op.drop_table('proveedor_items')
    op.drop_table('producto_fotos')
    op.drop_table('produccion')
    op.drop_table('ordenes')
    op.drop_table('notas_cliente')
    op.drop_table('movimientos')
    op.drop_table('mascotas')
    op.drop_table('direcciones')
    op.drop_table('compromisos')
    op.drop_table('usuarios')
    op.drop_table('tasas')
    op.drop_table('tarifas')
    op.drop_table('resultados_mes')
    op.drop_table('registro_ventas')
    op.drop_table('proveedores')
    op.drop_table('productos')
    op.drop_table('pagos_despachador')
    op.drop_table('notas_taller')
    op.drop_table('intentos')
    op.drop_table('faltas')
    op.drop_table('despachadores')
    op.drop_table('cuentas')
    op.drop_table('config')
    op.drop_table('clientes')
