-- Zonas que Cristina puso mirando el GPS de cada cliente (8 oct 2026). Solo las que existen en Tarifas.

UPDATE direcciones SET zona = '23 de enero' WHERE id = 237;
UPDATE direcciones SET zona = 'Altamira' WHERE id = 41;
UPDATE direcciones SET zona = 'Alto Prado' WHERE id = 180;
UPDATE direcciones SET zona = 'Bello Monte' WHERE id IN (243, 331);   -- Lomas de Bello Monte cuenta como Bello Monte
UPDATE direcciones SET zona = 'Boleita' WHERE id IN (275, 291);
UPDATE direcciones SET zona = 'Campo Alegre' WHERE id = 368;
UPDATE direcciones SET zona = 'Chacao' WHERE id IN (278, 360);
UPDATE direcciones SET zona = 'Chuao' WHERE id IN (197, 279);
UPDATE direcciones SET zona = 'Colinas de La Tahona' WHERE id = 282;
UPDATE direcciones SET zona = 'Cumbres de Curumo' WHERE id IN (101, 194, 376);
UPDATE direcciones SET zona = 'El Cafetal' WHERE id = 91;
UPDATE direcciones SET zona = 'El Cementerio' WHERE id IN (171, 315);
UPDATE direcciones SET zona = 'El Llanito' WHERE id = 256;
UPDATE direcciones SET zona = 'El Paraiso' WHERE id IN (37, 267, 321, 353);
UPDATE direcciones SET zona = 'El Peñón' WHERE id = 15;
UPDATE direcciones SET zona = 'El Recreo' WHERE id = 366;
UPDATE direcciones SET zona = 'El Rosal' WHERE id = 299;
UPDATE direcciones SET zona = 'El Valle' WHERE id IN (40, 322);
UPDATE direcciones SET zona = 'Francisco de Miranda' WHERE id = 231;
UPDATE direcciones SET zona = 'Fuerte Tiuna' WHERE id = 355;
UPDATE direcciones SET zona = 'La Alameda' WHERE id = 350;
UPDATE direcciones SET zona = 'La California Sur' WHERE id = 155;
UPDATE direcciones SET zona = 'La Candelaria' WHERE id = 100;
UPDATE direcciones SET zona = 'La Castellana' WHERE id IN (46, 102);
UPDATE direcciones SET zona = 'La Florida' WHERE id = 22;
UPDATE direcciones SET zona = 'La Guairita' WHERE id = 385;
UPDATE direcciones SET zona = 'La Lagunita' WHERE id = 274;
UPDATE direcciones SET zona = 'La Tahona' WHERE id = 226;
UPDATE direcciones SET zona = 'La Urbina' WHERE id IN (199, 213, 378);
UPDATE direcciones SET zona = 'Las Acacias' WHERE id IN (95, 297);
UPDATE direcciones SET zona = 'Las Palmas' WHERE id = 158;
UPDATE direcciones SET zona = 'Loma Linda' WHERE id = 326;
UPDATE direcciones SET zona = 'Lomas de Las Mercedes' WHERE id = 359;
UPDATE direcciones SET zona = 'Lomas del Sol' WHERE id = 55;
UPDATE direcciones SET zona = 'Los Campitos' WHERE id = 308;
UPDATE direcciones SET zona = 'Los Chaguaramos' WHERE id = 202;
UPDATE direcciones SET zona = 'Los Naranjos' WHERE id = 25;
UPDATE direcciones SET zona = 'Los Palos Grandes' WHERE id IN (151, 289, 354);
UPDATE direcciones SET zona = 'Los Samanes' WHERE id = 170;
UPDATE direcciones SET zona = 'Los Simbolos' WHERE id = 66;
UPDATE direcciones SET zona = 'Macaracuay' WHERE id = 301;
UPDATE direcciones SET zona = 'Macarao' WHERE id = 294;
UPDATE direcciones SET zona = 'Manzanares' WHERE id = 349;
UPDATE direcciones SET zona = 'Montalban' WHERE id IN (76, 90, 186);
UPDATE direcciones SET zona = 'Prados del Este' WHERE id = 325;
UPDATE direcciones SET zona = 'Quinta Crespo' WHERE id = 290;
UPDATE direcciones SET zona = 'San Bernardino' WHERE id = 255;
UPDATE direcciones SET zona = 'San Martín' WHERE id = 344;
UPDATE direcciones SET zona = 'San Roman' WHERE id = 36;
UPDATE direcciones SET zona = 'Santa Eduvigis' WHERE id = 208;
UPDATE direcciones SET zona = 'Santa Monica' WHERE id IN (259, 369);
UPDATE direcciones SET zona = 'Santa Paula' WHERE id = 384;
UPDATE direcciones SET zona = 'Sarria' WHERE id = 144;
UPDATE direcciones SET zona = 'Terrazas del Ávila' WHERE id IN (67, 288);
UPDATE direcciones SET zona = 'Vista Alegre' WHERE id = 140;

-- Zonas nuevas en Tarifas con el precio que dio Cristina (todas de Caracas), y sus clientes.
INSERT OR IGNORE INTO tarifas (zona, tarifa) SELECT 'El Pedregal', 5 WHERE EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Chacao');
INSERT OR IGNORE INTO tarifas (zona, tarifa) SELECT 'Monte Elena', 10 WHERE EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Chacao');
INSERT OR IGNORE INTO tarifas (zona, tarifa) SELECT 'Colinas de La Trinidad', 5 WHERE EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Chacao');
INSERT OR IGNORE INTO tarifas (zona, tarifa) SELECT 'Los Naranjos del Cafetal', 5 WHERE EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Chacao');
INSERT OR IGNORE INTO tarifas (zona, tarifa) SELECT 'El Helicoide', 6 WHERE EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Chacao');
INSERT OR IGNORE INTO tarifas (zona, tarifa) SELECT 'UCV', 5 WHERE EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Chacao');
INSERT OR IGNORE INTO tarifas (zona, tarifa) SELECT 'Caurimare', 5 WHERE EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Chacao');
UPDATE direcciones SET zona = 'El Pedregal' WHERE id = 373;
UPDATE direcciones SET zona = 'Monte Elena' WHERE id = 251;
UPDATE direcciones SET zona = 'Colinas de La Trinidad' WHERE id = 249;
UPDATE direcciones SET zona = 'Los Naranjos del Cafetal' WHERE id = 203;
UPDATE direcciones SET zona = 'El Helicoide' WHERE id = 200;
UPDATE direcciones SET zona = 'UCV' WHERE id = 150;
UPDATE direcciones SET zona = 'Caurimare' WHERE id = 45;
INSERT OR IGNORE INTO tarifas (zona, tarifa) SELECT 'Lomas de La Lagunita', 7 WHERE EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Chacao');
UPDATE direcciones SET zona = 'Lomas de La Lagunita' WHERE id = 293;
