-- Las zonas bien escritas, con sus acentos (Cristina, 8 oct 2026). Solo cambia el nombre: los precios no se tocan,
-- y los clientes y pedidos con esa zona pasan al nombre nuevo.

UPDATE tarifas SET zona = '23 de Enero' WHERE zona = '23 de enero' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = '23 de Enero');
UPDATE direcciones SET zona = '23 de Enero' WHERE zona = '23 de enero';
UPDATE ordenes SET zona = '23 de Enero' WHERE zona = '23 de enero';
UPDATE tarifas SET zona = 'Andrés Bello' WHERE zona = 'Andres Bello' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Andrés Bello');
UPDATE direcciones SET zona = 'Andrés Bello' WHERE zona = 'Andres Bello';
UPDATE ordenes SET zona = 'Andrés Bello' WHERE zona = 'Andres Bello';
UPDATE tarifas SET zona = 'Antímano' WHERE zona = 'Antimano' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Antímano');
UPDATE direcciones SET zona = 'Antímano' WHERE zona = 'Antimano';
UPDATE ordenes SET zona = 'Antímano' WHERE zona = 'Antimano';
UPDATE tarifas SET zona = 'Avenida Panteón' WHERE zona = 'Avenida Panteon' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Avenida Panteón');
UPDATE direcciones SET zona = 'Avenida Panteón' WHERE zona = 'Avenida Panteon';
UPDATE ordenes SET zona = 'Avenida Panteón' WHERE zona = 'Avenida Panteon';
UPDATE tarifas SET zona = 'Boleíta' WHERE zona = 'Boleita' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Boleíta');
UPDATE direcciones SET zona = 'Boleíta' WHERE zona = 'Boleita';
UPDATE ordenes SET zona = 'Boleíta' WHERE zona = 'Boleita';
UPDATE tarifas SET zona = 'Chacaíto' WHERE zona = 'Chacaito' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Chacaíto');
UPDATE direcciones SET zona = 'Chacaíto' WHERE zona = 'Chacaito';
UPDATE ordenes SET zona = 'Chacaíto' WHERE zona = 'Chacaito';
UPDATE tarifas SET zona = 'Chapellín' WHERE zona = 'Chapellin' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Chapellín');
UPDATE direcciones SET zona = 'Chapellín' WHERE zona = 'Chapellin';
UPDATE ordenes SET zona = 'Chapellín' WHERE zona = 'Chapellin';
UPDATE tarifas SET zona = 'Colinas de Santa Mónica' WHERE zona = 'Colinas de Santa Monica' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Colinas de Santa Mónica');
UPDATE direcciones SET zona = 'Colinas de Santa Mónica' WHERE zona = 'Colinas de Santa Monica';
UPDATE ordenes SET zona = 'Colinas de Santa Mónica' WHERE zona = 'Colinas de Santa Monica';
UPDATE tarifas SET zona = 'El Paraíso' WHERE zona = 'El Paraiso' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = 'El Paraíso');
UPDATE direcciones SET zona = 'El Paraíso' WHERE zona = 'El Paraiso';
UPDATE ordenes SET zona = 'El Paraíso' WHERE zona = 'El Paraiso';
UPDATE tarifas SET zona = 'La Campiña' WHERE zona = 'La Campina' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = 'La Campiña');
UPDATE direcciones SET zona = 'La Campiña' WHERE zona = 'La Campina';
UPDATE ordenes SET zona = 'La Campiña' WHERE zona = 'La Campina';
UPDATE tarifas SET zona = 'La Unión' WHERE zona = 'La Union' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = 'La Unión');
UPDATE direcciones SET zona = 'La Unión' WHERE zona = 'La Union';
UPDATE ordenes SET zona = 'La Unión' WHERE zona = 'La Union';
UPDATE tarifas SET zona = 'Los Símbolos' WHERE zona = 'Los Simbolos' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Los Símbolos');
UPDATE direcciones SET zona = 'Los Símbolos' WHERE zona = 'Los Simbolos';
UPDATE ordenes SET zona = 'Los Símbolos' WHERE zona = 'Los Simbolos';
UPDATE tarifas SET zona = 'Montalbán' WHERE zona = 'Montalban' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Montalbán');
UPDATE direcciones SET zona = 'Montalbán' WHERE zona = 'Montalban';
UPDATE ordenes SET zona = 'Montalbán' WHERE zona = 'Montalban';
UPDATE tarifas SET zona = 'Naiguatá' WHERE zona = 'Naiguata' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Naiguatá');
UPDATE direcciones SET zona = 'Naiguatá' WHERE zona = 'Naiguata';
UPDATE ordenes SET zona = 'Naiguatá' WHERE zona = 'Naiguata';
UPDATE tarifas SET zona = 'Pérez Bonalde' WHERE zona = 'Perez Bonalde' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Pérez Bonalde');
UPDATE direcciones SET zona = 'Pérez Bonalde' WHERE zona = 'Perez Bonalde';
UPDATE ordenes SET zona = 'Pérez Bonalde' WHERE zona = 'Perez Bonalde';
UPDATE tarifas SET zona = 'Prado de María' WHERE zona = 'Prado de Maria' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Prado de María');
UPDATE direcciones SET zona = 'Prado de María' WHERE zona = 'Prado de Maria';
UPDATE ordenes SET zona = 'Prado de María' WHERE zona = 'Prado de Maria';
UPDATE tarifas SET zona = 'Río de Oro' WHERE zona = 'Rio de Oro' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Río de Oro');
UPDATE direcciones SET zona = 'Río de Oro' WHERE zona = 'Rio de Oro';
UPDATE ordenes SET zona = 'Río de Oro' WHERE zona = 'Rio de Oro';
UPDATE tarifas SET zona = 'Rómulo Gallegos' WHERE zona = 'Romulo Gallegos' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Rómulo Gallegos');
UPDATE direcciones SET zona = 'Rómulo Gallegos' WHERE zona = 'Romulo Gallegos';
UPDATE ordenes SET zona = 'Rómulo Gallegos' WHERE zona = 'Romulo Gallegos';
UPDATE tarifas SET zona = 'San Agustín' WHERE zona = 'San Agustin' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = 'San Agustín');
UPDATE direcciones SET zona = 'San Agustín' WHERE zona = 'San Agustin';
UPDATE ordenes SET zona = 'San Agustín' WHERE zona = 'San Agustin';
UPDATE tarifas SET zona = 'San Román' WHERE zona = 'San Roman' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = 'San Román');
UPDATE direcciones SET zona = 'San Román' WHERE zona = 'San Roman';
UPDATE ordenes SET zona = 'San Román' WHERE zona = 'San Roman';
UPDATE tarifas SET zona = 'Santa Inés' WHERE zona = 'Santa Ines' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Santa Inés');
UPDATE direcciones SET zona = 'Santa Inés' WHERE zona = 'Santa Ines';
UPDATE ordenes SET zona = 'Santa Inés' WHERE zona = 'Santa Ines';
UPDATE tarifas SET zona = 'Santa Mónica' WHERE zona = 'Santa Monica' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Santa Mónica');
UPDATE direcciones SET zona = 'Santa Mónica' WHERE zona = 'Santa Monica';
UPDATE ordenes SET zona = 'Santa Mónica' WHERE zona = 'Santa Monica';
UPDATE tarifas SET zona = 'Santa Rosalía' WHERE zona = 'Santa Rosalia' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Santa Rosalía');
UPDATE direcciones SET zona = 'Santa Rosalía' WHERE zona = 'Santa Rosalia';
UPDATE ordenes SET zona = 'Santa Rosalía' WHERE zona = 'Santa Rosalia';
UPDATE tarifas SET zona = 'Sebucán' WHERE zona = 'Sebucan' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Sebucán');
UPDATE direcciones SET zona = 'Sebucán' WHERE zona = 'Sebucan';
UPDATE ordenes SET zona = 'Sebucán' WHERE zona = 'Sebucan';
UPDATE tarifas SET zona = 'Lebrún' WHERE zona = 'Lebrun' AND NOT EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Lebrún');
UPDATE direcciones SET zona = 'Lebrún' WHERE zona = 'Lebrun';
UPDATE ordenes SET zona = 'Lebrún' WHERE zona = 'Lebrun';

-- "Pago Verde" era un error de "Palo Verde": lo que la tenía pasa a Palo Verde y se borra.
UPDATE direcciones SET zona = 'Palo Verde' WHERE zona = 'Pago Verde' AND EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Palo Verde');
UPDATE ordenes SET zona = 'Palo Verde' WHERE zona = 'Pago Verde' AND EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Palo Verde');
DELETE FROM tarifas WHERE zona = 'Pago Verde' AND EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Palo Verde');

-- Zonas nuevas a $5 (todas de Caracas) y los clientes que las tienen.
INSERT OR IGNORE INTO tarifas (zona, tarifa) SELECT 'Puente Hierro', 5 WHERE EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Chacao');
UPDATE direcciones SET zona = 'Puente Hierro' WHERE id = 115 AND EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Puente Hierro');
INSERT OR IGNORE INTO tarifas (zona, tarifa) SELECT 'Los Naranjos de Las Mercedes', 5 WHERE EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Chacao');
UPDATE direcciones SET zona = 'Los Naranjos de Las Mercedes' WHERE id = 185 AND EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Los Naranjos de Las Mercedes');
INSERT OR IGNORE INTO tarifas (zona, tarifa) SELECT 'San Luis', 5 WHERE EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Chacao');
UPDATE direcciones SET zona = 'San Luis' WHERE id = 271 AND EXISTS (SELECT 1 FROM tarifas WHERE zona = 'San Luis');
INSERT OR IGNORE INTO tarifas (zona, tarifa) SELECT 'Lomas de Las Acacias', 5 WHERE EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Chacao');
UPDATE direcciones SET zona = 'Lomas de Las Acacias' WHERE id = 303 AND EXISTS (SELECT 1 FROM tarifas WHERE zona = 'Lomas de Las Acacias');
